fail_fast: true
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: security
        name: security
        entry: make security
        language: system
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: make requirements
        language: system
        pass_filenames: false
        stages: [pre-commit]
